# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - main.css
    - "/css/smoothness/jquery-ui-1.8.2.custom.css"

  javascripts:
    - "/js/lib/jquery-1.4.2.js"
    - "/js/lib/jquery-ui-1.8.2.custom.min.js"
    - main
    

  has_layout:     true
  layout:         layout
